// let promise = new Promise((resolve, reject) => {
//     console.log('promise');

//     //resolve();
//     reject(x+2);
//     //throw Error('oh error');
// });

// promise.catch(err=>{
//     console.log('error: ' + err);
// }).then(()=>{
//     console.log('carray on');
//     throw Error('carray on failed.');
// }).catch((err)=>{
//     console.log('error 2: ' + err);
// });

const p = Promise.all([])